import type { Level } from './types';

export const LEVELS: Level[] = [
  {
    id: 1,
    title: '直线对焦',
    hint: '激光已对准终点，点击「下一关」继续。',
    cols: 8,
    rows: 5,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 6.5, y: 2.5 },
    mirrors: [],
    nodes: [],
    walls: [],
  },
  {
    id: 2,
    title: '初次反射',
    hint: '点击镜子旋转角度，把激光折向正下方终点。',
    cols: 6,
    rows: 5,
    source: { x: 0.5, y: 1.5, angle: 0 },
    goal: { x: 3.5, y: 3.5 },
    mirrors: [{ id: 'm1', x: 3.5, y: 1.5, angle: 0 }],
    nodes: [],
    walls: [],
  },
  {
    id: 3,
    title: '绕墙而行',
    hint: '中间有墙壁阻挡，用两面镜子先向下再折向东绕过障碍。',
    cols: 9,
    rows: 5,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 7.5, y: 3.5 },
    mirrors: [
      { id: 'm1', x: 2.5, y: 2.5, angle: 0 },
      { id: 'm2', x: 2.5, y: 3.5, angle: 0 },
    ],
    nodes: [],
    walls: [
      { x: 4, y: 2 },
      { x: 5, y: 2 },
    ],
  },
  {
    id: 4,
    title: '能量节点',
    hint: '激光必须先经过黄色能量节点，再到达绿色终点。',
    cols: 8,
    rows: 5,
    source: { x: 0.5, y: 1.5, angle: 0 },
    goal: { x: 5.5, y: 3.5 },
    mirrors: [{ id: 'm1', x: 5.5, y: 1.5, angle: 0 }],
    nodes: [{ id: 'n1', x: 3.5, y: 1.5 }],
    walls: [],
  },
  {
    id: 5,
    title: '双镜连环',
    hint: '调整两面镜子绕过墙壁，经过下方两个能量节点抵达终点。',
    cols: 9,
    rows: 5,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 7.5, y: 3.5 },
    mirrors: [
      { id: 'm1', x: 2.5, y: 2.5, angle: 0 },
      { id: 'm2', x: 2.5, y: 3.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 4.5, y: 3.5 },
      { id: 'n2', x: 6.5, y: 3.5 },
    ],
    walls: [
      { x: 4, y: 2 },
      { x: 5, y: 2 },
    ],
  },
  {
    id: 6,
    title: '上层突围',
    hint: '激光沿底部走廊前进，再两次折向顶部。中间墙壁封锁了所有捷径。',
    cols: 10,
    rows: 6,
    source: { x: 0.5, y: 4.5, angle: 0 },
    goal: { x: 9.5, y: 0.5 },
    mirrors: [
      { id: 'm1', x: 3.5, y: 4.5, angle: 0 },
      { id: 'm2', x: 3.5, y: 0.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 2.5, y: 4.5 },
      { id: 'n2', x: 7.5, y: 0.5 },
    ],
    walls: [
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
      { x: 7, y: 2 },
      { x: 4, y: 3 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
      { x: 7, y: 3 },
    ],
  },
  {
    id: 7,
    title: '三线汇能',
    hint: '三面镜子构成 U 形折路，依次激活三个能量节点。注意上方横向墙壁。',
    cols: 10,
    rows: 5,
    source: { x: 0.5, y: 1.5, angle: 0 },
    goal: { x: 9.5, y: 1.5 },
    mirrors: [
      { id: 'm1', x: 3.5, y: 1.5, angle: 0 },
      { id: 'm2', x: 3.5, y: 3.5, angle: 0 },
      { id: 'm3', x: 8.5, y: 3.5, angle: 0 },
      { id: 'm4', x: 8.5, y: 1.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 2.5, y: 1.5 },
      { id: 'n2', x: 5.5, y: 3.5 },
      { id: 'n3', x: 7.5, y: 3.5 },
    ],
    walls: [
      { x: 5, y: 1 },
      { x: 6, y: 1 },
      { x: 7, y: 1 },
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
      { x: 7, y: 2 },
    ],
  },
  {
    id: 8,
    title: '纵向迂回',
    hint: '从底部出发，沿左侧上行再折向顶部终点。中央墙体形成大型障碍区。',
    cols: 11,
    rows: 6,
    source: { x: 0.5, y: 5.5, angle: 0 },
    goal: { x: 9.5, y: 0.5 },
    mirrors: [
      { id: 'm1', x: 4.5, y: 5.5, angle: 0 },
      { id: 'm2', x: 4.5, y: 2.5, angle: 0 },
      { id: 'm3', x: 9.5, y: 2.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 2.5, y: 5.5 },
      { id: 'n2', x: 6.5, y: 2.5 },
      { id: 'n3', x: 7.5, y: 2.5 },
    ],
    walls: [
      { x: 5, y: 3 },
      { x: 6, y: 3 },
      { x: 7, y: 3 },
      { x: 8, y: 3 },
      { x: 5, y: 4 },
      { x: 6, y: 4 },
      { x: 7, y: 4 },
      { x: 8, y: 4 },
    ],
  },
  {
    id: 9,
    title: '四面夹击',
    hint: '五面镜子构成 S 形折路：先向上绕障，再折回下方，最后升至终点。',
    cols: 11,
    rows: 6,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 10.5, y: 4.5 },
    mirrors: [
      { id: 'm1', x: 2.5, y: 2.5, angle: 0 },
      { id: 'm2', x: 2.5, y: 4.5, angle: 0 },
      { id: 'm3', x: 8.5, y: 4.5, angle: 0 },
      { id: 'm4', x: 8.5, y: 1.5, angle: 0 },
      { id: 'm5', x: 10.5, y: 1.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 1.5, y: 2.5 },
      { id: 'n2', x: 4.5, y: 4.5 },
      { id: 'n3', x: 7.5, y: 4.5 },
      { id: 'n4', x: 10.5, y: 2.5 },
    ],
    walls: [
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
      { x: 4, y: 3 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
  },
  {
    id: 10,
    title: '天顶垂落',
    hint: '激光从顶部垂直射下，需用镜子将它折向底部终点。墙壁封锁了直线通道。',
    cols: 9,
    rows: 7,
    source: { x: 4.5, y: 0.5, angle: 90 },
    goal: { x: 7.5, y: 6.5 },
    mirrors: [
      { id: 'm1', x: 4.5, y: 3.5, angle: 0 },
      { id: 'm2', x: 7.5, y: 3.5, angle: 0 },
      { id: 'm3', x: 7.5, y: 5.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 4.5, y: 2.5 },
      { id: 'n2', x: 6.5, y: 3.5 },
    ],
    walls: [
      { x: 4, y: 5 },
      { x: 5, y: 5 },
      { x: 6, y: 5 },
      { x: 4, y: 6 },
      { x: 5, y: 6 },
      { x: 6, y: 6 },
    ],
  },
  {
    id: 11,
    title: '节点密阵',
    hint: '在「四面夹击」基础上延伸：最后一面镜子负责将激光折向远端终点。',
    cols: 12,
    rows: 6,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 11.5, y: 4.5 },
    mirrors: [
      { id: 'm1', x: 2.5, y: 2.5, angle: 0 },
      { id: 'm2', x: 2.5, y: 4.5, angle: 0 },
      { id: 'm3', x: 8.5, y: 4.5, angle: 0 },
      { id: 'm4', x: 8.5, y: 1.5, angle: 0 },
      { id: 'm5', x: 10.5, y: 1.5, angle: 0 },
      { id: 'm6', x: 10.5, y: 4.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 1.5, y: 2.5 },
      { id: 'n2', x: 4.5, y: 4.5 },
      { id: 'n3', x: 7.5, y: 4.5 },
      { id: 'n4', x: 10.5, y: 2.5 },
    ],
    walls: [
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
      { x: 4, y: 3 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
  },
  {
    id: 12,
    title: '光学终试',
    hint: '终极 S 形双折路：七面镜子串联上下两层通道，五处节点分布在折线各段。',
    cols: 12,
    rows: 7,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 11.5, y: 5.5 },
    mirrors: [
      { id: 'm1', x: 2.5, y: 2.5, angle: 0 },
      { id: 'm2', x: 2.5, y: 4.5, angle: 0 },
      { id: 'm3', x: 8.5, y: 4.5, angle: 0 },
      { id: 'm4', x: 8.5, y: 1.5, angle: 0 },
      { id: 'm5', x: 10.5, y: 1.5, angle: 0 },
      { id: 'm6', x: 10.5, y: 4.5, angle: 0 },
      { id: 'm7', x: 11.5, y: 4.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 1.5, y: 2.5 },
      { id: 'n2', x: 4.5, y: 4.5 },
      { id: 'n3', x: 7.5, y: 4.5 },
      { id: 'n4', x: 10.5, y: 2.5 },
      { id: 'n5', x: 10.5, y: 3.5 },
    ],
    walls: [
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
      { x: 4, y: 3 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
      { x: 4, y: 5 },
      { x: 5, y: 5 },
      { x: 6, y: 5 },
    ],
  },
];
