import type { Level } from './types';

export const LEVELS: Level[] = [
  {
    id: 1,
    title: '直线对焦',
    hint: '激光已对准终点，点击「下一关」继续。',
    cols: 8,
    rows: 5,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 6.5, y: 2.5 },
    mirrors: [],
    nodes: [],
    walls: [],
  },
  {
    id: 2,
    title: '初次反射',
    hint: '点击镜子旋转角度，把激光折向正下方终点。',
    cols: 6,
    rows: 5,
    source: { x: 0.5, y: 1.5, angle: 0 },
    goal: { x: 3.5, y: 3.5 },
    mirrors: [{ id: 'm1', x: 3.5, y: 1.5, angle: 0 }],
    nodes: [],
    walls: [],
  },
  {
    id: 3,
    title: '绕墙而行',
    hint: '中间有墙壁阻挡，用两面镜子先向下再折向东绕过障碍。',
    cols: 9,
    rows: 5,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 7.5, y: 3.5 },
    mirrors: [
      { id: 'm1', x: 2.5, y: 2.5, angle: 0 },
      { id: 'm2', x: 2.5, y: 3.5, angle: 0 },
    ],
    nodes: [],
    walls: [
      { x: 4, y: 2 },
      { x: 5, y: 2 },
    ],
  },
  {
    id: 4,
    title: '能量节点',
    hint: '激光必须先经过黄色能量节点，再到达绿色终点。',
    cols: 8,
    rows: 5,
    source: { x: 0.5, y: 1.5, angle: 0 },
    goal: { x: 5.5, y: 3.5 },
    mirrors: [{ id: 'm1', x: 5.5, y: 1.5, angle: 0 }],
    nodes: [{ id: 'n1', x: 3.5, y: 1.5 }],
    walls: [],
  },
  {
    id: 5,
    title: '双镜连环',
    hint: '调整两面镜子绕过墙壁，经过下方两个能量节点抵达终点。',
    cols: 9,
    rows: 5,
    source: { x: 0.5, y: 2.5, angle: 0 },
    goal: { x: 7.5, y: 3.5 },
    mirrors: [
      { id: 'm1', x: 2.5, y: 2.5, angle: 0 },
      { id: 'm2', x: 2.5, y: 3.5, angle: 0 },
    ],
    nodes: [
      { id: 'n1', x: 4.5, y: 3.5 },
      { id: 'n2', x: 6.5, y: 3.5 },
    ],
    walls: [
      { x: 4, y: 2 },
      { x: 5, y: 2 },
    ],
  },
];
